package com.mystic.tarotboard.scenes;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import com.mystic.tarotboard.utils.Styles;

/**
 * Manages the display of the help content scene in the TarotBoard application.
 * This scene provides users with information about keybinds, deck structure,
 * hand rankings, scoring, and other game-related details.
 */
public class HelpScene {

    /**
     * Private constructor to prevent instantiation of this utility class.
     */
    private HelpScene() {
    }

    /**
     * Displays the help content scene on the given stage.
     * <p>
     * This method sets up the UI for the help section, including a scrollable
     * container for the content generated by {@link HelpContent}, and a back button
     * to return to the previous scene.
     *
     * @param stage The primary stage of the JavaFX application where the scene will be displayed.
     */
    public static void show(Stage stage) {
        Scene previousScene = stage.getScene();
        VBox contentContainer = new VBox(12);
        contentContainer.setPadding(new Insets(20));
        contentContainer.setStyle("-fx-background-color: black;");

        HelpContent.buildContent(contentContainer);

        ScrollPane scrollPane = new ScrollPane(contentContainer);
        scrollPane.setFitToWidth(true);
        scrollPane.setPannable(true);
        scrollPane.setStyle("-fx-background: transparent; -fx-background-color: gray;");
        VBox.setVgrow(scrollPane, Priority.ALWAYS);

        Button backButton = new Button("Back");
        backButton.setStyle(Styles.helpBtn());
        backButton.setOnAction(event -> stage.setScene(previousScene));

        HBox buttonBox = new HBox(backButton);
        buttonBox.setAlignment(Pos.CENTER);
        buttonBox.setPadding(new Insets(15));

        VBox layout = new VBox(scrollPane, buttonBox);
        layout.setAlignment(Pos.TOP_CENTER);

        Scene scene = new Scene(layout, 450, 750);
        Styles.applyBackgroundImage(layout);
        stage.setScene(scene);
    }
}
