name: Build & Publish Release APK

on:
  push:
    branches: [master ]
  pull_request:
  workflow_dispatch:

jobs:
  android:
    name: Build Android Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Android APK
        uses: Kishanjvaghela/build-and-release-apk@v1
        with:
          command: assembleRelease
          build_type: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
