name: Build And Release Linux And Windows Builds

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    name: Windows (MSI + EXE)
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        type: [ msi, exe ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build ${{ matrix.type }}
        run: ./gradlew.bat clean jpackage -PinstallerType=${{ matrix.type }}
        shell: cmd

      - name: Upload ${{ matrix.type }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.type }}-build
          path: build/jpackage/TarotBoard-*.${{ matrix.type }}
          compression-level: 0
          if-no-files-found: error

  linux:
    name: Linux (AppImage)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install fakeroot
        run: sudo apt-get update -qq && sudo apt-get install -y -qq fakeroot

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build AppImage
        run: ./gradlew clean jpackage -PinstallerType=app-image

      - name: Archive AppImage
        run: tar -czf TarotBoard-linux-appimage.tar.gz -C build/jpackage TarotBoard/

      - name: Upload AppImage archive
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage-build
          path: TarotBoard-linux-appimage.tar.gz
          compression-level: 6
          if-no-files-found: error
  android:
    name: Android (APK)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Verify Java and GraalVM setup
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java -version
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          $GRAALVM_HOME/bin/java -version
          echo GRAALVM_HOME
          native-image --version

      - name: Build APK
        env:
          GRAALVM_HOME: $GRAALVM_HOME
        run: ./gradlew nativePackage -PandroidBuild=true --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-build
          path: build/gluonfx/aarch64-android/TarotBoard.apk
          compression-level: 0
          if-no-files-found: error
